"""add user

Revision ID: 643da79abbc4
Revises: 0e61c8ea10e4
Create Date: 2021-02-04 16:16:42.319610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643da79abbc4'
down_revision = '0e61c8ea10e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('login', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARBINARY(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.add_column('employees', sa.Column('user_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
